### ISSUE TITLE
Kleiner Hinweis

### ISSUE THREAD

**Issue by Cr4zyc4k3** [Sobol0202/LSS-EasterEggHunter#1]
https://github.com/Sobol0202/LSS-EasterEggHunter/blob/e1f52c4e8e42572292a79dbe866d6812c4cd4d99/LSS%20Easter%20Egg%20Checker.user.js#L33

Jfyi: `math.random()` spuckt dir eine Zahl zwischen 0 und <1 aus. Somit ist der Wert zwischen 0,5 und 1,4999 
😄

**Comment by Sobol0202** [comment]
Ursprünglich hatte ich dort eine etwas andere Zeile drin und hatte bei der änderung im Code vergessen den Comment anzupassen. 
In v1.2 fixed
